name: 'Scan'
description: 'Lint, SAST, SCA, IaC, and secret scans'
outputs:
  ref:
    description: 'The branch, tag or SHA that was checked out'
  commit:
    description: 'The commit SHA that was checked out'
runs:
  using: node24
  main: src/index.js
  post: src/index.js