on:
  workflow_run:
    workflows: [ci.yml]
    types: [completed]
    branches: [main]

jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    description: "Deploy to QA environment"
    steps:
      - uses: actions/checkout@v08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: phronesis-labs/deploy@v1.0.0
        with:
          environment: qa

  deploy-staging:
    runs-on: ubuntu-latest
    needs: deploy-qa
    description: "Deploy to Staging environment"
    steps:
      - uses: actions/checkout@v08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: phronesis-labs/deploy@v1.0.0
        with:
          environment: staging

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    description: "Deploy to Production environment"
    steps:
      - uses: actions/checkout@v08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: phronesis-labs/deploy@v1.0.0
        with:
          environment: production
          approval-required: true