on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    description: "Lint, SAST, SCA, IaC, and secret scans"
    steps:
      - uses: actions/checkout@v08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Scan
        uses: phronesis-labs/scan@v1.0.0
  
  unit-test:
    runs-on: ubuntu-latest
    needs: scan
    description: "Unit tests"
    steps:
      - uses: actions/checkout@v08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Unit Test
        uses: phronesis-labs/unit-test@v1.0.0

  build:
    runs-on: ubuntu-latest
    needs: [scan, unit-test]
    description: "Build, scan, tag, and publish container image"
    steps:
      - uses: actions/checkout@v08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build
        uses: phronesis-labs/build@v1.0.0
